// Shared lead data for the three dashboard variants.
window.LEADS = [
  {
    id: "L-2918",
    name: "Priya Raghavan",
    initials: "PR",
    title: "VP Engineering",
    company: "Northwind Labs",
    domain: "northwindlabs.com",
    location: "San Francisco, CA",
    employees: 480,
    score: 94,
    temp: "hot",
    stage: "Engaged",
    owner: "You",
    source: "Demo request",
    lastActivity: "12 min ago",
    lastActivityRaw: 12,
    unread: 2,
    signals: [
      { label: "Booked demo from /pricing", weight: "strong" },
      { label: "Series C announced ($48M)", weight: "strong" },
      { label: "3 teammates added to workspace", weight: "medium" },
    ],
    summary:
      "Priya booked a 30-min demo twelve minutes ago from /pricing — her second visit this week. Northwind just closed a $48M Series C and three teammates have joined her trial workspace.",
    rec: "Call within the hour. Lead with platform reliability — she searched 'SLA' twice.",
    confidence: 92,
    intent: ["pricing", "SLA", "SOC2"],
  },
  {
    id: "L-2914",
    name: "Arjun Kapoor",
    initials: "AK",
    title: "Head of RevOps",
    company: "Halcyon Health",
    domain: "halcyonhealth.io",
    location: "Austin, TX",
    employees: 1200,
    score: 89,
    temp: "hot",
    stage: "Qualifying",
    owner: "You",
    source: "Inbound chat",
    lastActivity: "2 h ago",
    lastActivityRaw: 120,
    unread: 1,
    signals: [
      { label: "Mid-vendor evaluation (G2 comparison opened)", weight: "strong" },
      { label: "Replied within 4 minutes last 3 emails", weight: "medium" },
      { label: "Forwarded thread to CFO", weight: "medium" },
    ],
    summary:
      "Marcus is two weeks into a three-vendor bake-off. He forwards every message to his CFO within an hour. Reply speed is the variable that wins this.",
    rec: "Send the procurement-friendly one-pager and propose a 15-min CFO Q&A this week.",
    confidence: 86,
    intent: ["pricing", "procurement", "security"],
  },
  {
    id: "L-2909",
    name: "Vikram Iyer",
    initials: "VI",
    title: "Founder",
    company: "Spool",
    domain: "spool.dev",
    location: "Remote · EU",
    employees: 14,
    score: 81,
    temp: "hot",
    stage: "New",
    owner: "Dani Park",
    source: "Referral",
    lastActivity: "Yesterday",
    lastActivityRaw: 1440,
    unread: 0,
    signals: [
      { label: "Referral from Ada @ Tessera (paying customer)", weight: "strong" },
      { label: "Founder, decision-maker", weight: "medium" },
    ],
    summary:
      "Daniel was introduced personally by Ada at Tessera, one of our top three customers. Founder-led, fourteen people, short cycle. He won't read a sequence.",
    rec: "Skip the deck. Offer a 20-minute working session to map his pipeline live.",
    confidence: 78,
    intent: ["onboarding", "trial"],
  },
  {
    id: "L-2901",
    name: "Ananya Nair",
    initials: "AN",
    title: "General Counsel",
    company: "Kestrel Group",
    domain: "kestrel.co.nz",
    location: "Bengaluru, IN",
    employees: 320,
    score: 76,
    temp: "warm",
    stage: "Opportunity",
    owner: "You",
    source: "Event",
    lastActivity: "3 d ago",
    lastActivityRaw: 4320,
    unread: 0,
    signals: [
      { label: "Redlined MSA returned", weight: "strong" },
      { label: "Counsel out until Tuesday", weight: "weak" },
    ],
    summary:
      "Ananya returned the MSA with light redlines. Her counsel is travelling until Tuesday — nothing moves until then.",
    rec: "Send the clean MSA Monday 8am IST so it's at the top of her inbox.",
    confidence: 81,
    intent: ["legal", "MSA"],
  },
  {
    id: "L-2896",
    name: "Meera Bhatia",
    initials: "MB",
    title: "VP Sales (interim)",
    company: "Brightline",
    domain: "brightline.so",
    location: "New York, NY",
    employees: 95,
    score: 64,
    temp: "warm",
    stage: "Nurture",
    owner: "Alex Romano",
    source: "Webinar",
    lastActivity: "5 d ago",
    lastActivityRaw: 7200,
    unread: 0,
    signals: [
      { label: "CRO search underway", weight: "medium" },
      { label: "Attended Q3 product webinar", weight: "weak" },
    ],
    summary:
      "Brightline is between sales leaders — Meera is interim. Final decisions paused until a CRO is named.",
    rec: "Move to Nurture. Re-engage when the CRO hire is announced.",
    confidence: 70,
    intent: ["hiring"],
  },
  {
    id: "L-2890",
    name: "Karan Malhotra",
    initials: "KM",
    title: "Director of Platform",
    company: "Mira & Co.",
    domain: "miraandco.com",
    location: "Mumbai, IN",
    employees: 210,
    score: 58,
    temp: "warm",
    stage: "Qualifying",
    owner: "Dani Park",
    source: "Content download",
    lastActivity: "6 d ago",
    lastActivityRaw: 8640,
    unread: 0,
    signals: [
      { label: "Downloaded 'Pipeline ops playbook'", weight: "medium" },
      { label: "Returned to docs 4× this week", weight: "medium" },
    ],
    summary:
      "Karan downloaded the ops playbook and has been quietly reading the docs all week. Research mode — not yet ready for a call.",
    rec: "Send the implementation case study, no calendar link.",
    confidence: 64,
    intent: ["docs", "implementation"],
  },
  {
    id: "L-2882",
    name: "Sneha Patel",
    initials: "SP",
    title: "Operations Lead",
    company: "Atlas Freight",
    domain: "atlasfreight.com",
    location: "Pune, IN",
    employees: 640,
    score: 42,
    temp: "cold",
    stage: "Nurture",
    owner: "Unassigned",
    source: "Cold outbound",
    lastActivity: "2 w ago",
    lastActivityRaw: 20160,
    unread: 0,
    signals: [
      { label: "Opened 2 of 5 sequence emails", weight: "weak" },
    ],
    summary:
      "Cold outbound contact. Limited signal — opens but no clicks, no replies.",
    rec: "Drop from active sequence. Re-add Q1 when freight ops budgets reopen.",
    confidence: 55,
    intent: [],
  },
];

window.OWNER_COLORS = {
  "You":         { bg: "#f3d9bf", fg: "#5b2e0a", init: "SK", name: "Sam Kovacs" },
  "Dani Park":   { bg: "#c9dffb", fg: "#0f2e5c", init: "DP", name: "Dani Park" },
  "Alex Romano": { bg: "#d3ecd1", fg: "#1d4d1b", init: "AR", name: "Alex Romano" },
  "Unassigned":  { bg: "#e9e7e1", fg: "#6b6f77", init: "—", name: "Unassigned" },
};
